name: bloc_logger
description: Dart package for a bloc observer that prints output using loggy
version: 0.0.3-dev.9
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  bloc: ^8.0.3
  # analyzer
  dart_code_metrics: ^4.16.0
  logger: ^1.1.0

dev_dependencies:
  coverage: ^1.5.0
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: "^3.0.1"